# Setup
title: keosariel
url: https://keosariel.github.io
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
#  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: UA-180096782-1

# Specify the author for blog posts
author:
  name: kenneth Gabriel
  url: https://twitter.com/keosariel
  email: kennethgabriel78@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /archive
   
  - title: Projects
    url: /projects

  - title: About
    url: /about
